ORG 0H
NUM1 EQU 30H
NUM2 EQU 31H
OP EQU 32H
RESULT EQU 33H

MOV NUM1,#1H
MOV NUM2,#04H
MOV OP,#00H

MOV A,OP
MOV R2,A
MOV A,NUM2
MOV R1,A
MOV A,NUM1
MOV R0,A

                                    ;00H-ADDITION
CJNE R2,#00H,CHECKSUB               ;01H-SUBTRACTION 
ADD A,R1                            ;02H-MULTIPLICATION
SJMP STORE                          ;03H-DIVISION  

CHECKSUB:CJNE R2,#01H,CHECKMUL
MOV A,R0
SUBB A,R1
SJMP STORE

CHECKMUL:CJNE R2,#02H,CHECKDIV
MOV A,R0
MOV B,R1
MUL AB
SJMP STORE

CHECKDIV:CJNE R2,#03H,INVALID
MOV A,R0
MOV B,R1
DIV AB
SJMP STORE

INVALID:MOV A,#50H       ;MOV 50H IF OPERAND IS INVALID
STORE:MOV RESULT,A
HERE:SJMP HERE
END
